### PR TITLE
Implement unmatched_normal_ids

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**
This PR allows unmatched normal IDs to be associated with both seq_types and genome_builds. This PR is backwards-compatible with the old way of specifying `unmatched_normal_id` in the `pairing_config`. I need to update the docs in this branch before merging it into master.

### CODE REVIEW

**Comment by BrunoGrandePhD** [comment]
@lkhilton: Could you checkout the `bug-fix/unmatched_normal_ids` branch (after running `git fetch` first) and check if `oncopipe` behaves as I described in #52? I'll merge this PR once you confirm that things look good and once I update the docs. You can use this branch in the meantime rather than master. The only difference is this feature. Thanks!

**Comment by lkhilton** [comment]
I'm getting this error: 
```
AssertionError in line 64 of /projects/rmorin/projects/gambl-repos/gambl-lhilton/src/snakemake/header.smk:
There are 0 genome samples matching the normal ID {'genome--grch37': '14-11247N', 'genome--hg38': 'BLGSP-71-06-00286-99A-01D', 'genome--hs37d5': 'SP116656'} (instead of just one).
  File "/projects/rmorin/projects/gambl-repos/gambl-lhilton/src/snakemake/header.smk", line 64, in <module>
  File "/projects/rmorin/software/lcr-modules/oncopipe/oncopipe/__init__.py", line 1296, in generate_pairs
  File "/projects/rmorin/software/lcr-modules/oncopipe/oncopipe/__init__.py", line 1114, in generate_runs
```
The Snakefile looks like this: 
```
#!/usr/bin/env snakemake


##### MODULES #####


import os
import shutil
import oncopipe as op
from snakemake.logging import logger


##### SETUP #####


# Load general project configuration
configfile: "config/general.yaml"

# Load samples and filter for those with BAM files
SAMPLES = op.load_samples("data/metadata/gambl_samples_available.tsv")
SAMPLES = op.filter_samples(SAMPLES, bam_available = True)

# Obtain list of values that appear in the unix_group column
available_unix_groups = SAMPLES["unix_group"].unique().tolist()

# Default to gambl unix_group if not specified at the command line
if "unix_group" not in config:
    logger.warning(
        "Defaulting to 'gambl' unix_group. You can specify the unix_group at "
        "the command line using `--config unix_group=icgc_dart`, for example. "
        f"Here are the possible values for unix_group: {available_unix_groups}."
    )
    config["unix_group"] = "gambl"

# Check if provided unix_group is one that appears in the sample table
assert config["unix_group"] in available_unix_groups, (
    f"The '{config['unix_group']}' unix_group doesn't appear in the sample table. "
    f"Here are the possible values for unix_group: {available_unix_groups}."
)

# Subset samples for those matching the given unix_group
SAMPLES = op.filter_samples(SAMPLES, unix_group=config["unix_group"])

# Determine the output directory for the results of this unix_group by
# appending the lcr-modules root_output_dir with the unix_group name
shared_config = config["lcr-modules"]["_shared"]
PARENT_DIR = shared_config["root_output_dir"]
OUTPUT_DIR = os.path.join(PARENT_DIR, config['unix_group']) + "/"
shared_config["root_output_dir"] = OUTPUT_DIR

# Make sure the directory exists and has the right access permissions
# This can only be used if the directory doesn't already exist.
# os.makedirs(OUTPUT_DIR, exist_ok=True)
# shutil.chown(OUTPUT_DIR, group=config['unix_group'])
# os.chmod(OUTPUT_DIR, mode=0o770)

# Create convenient sample subsets
GENOMES = op.filter_samples(SAMPLES, seq_type="genome")
RNASEQS = op.filter_samples(SAMPLES, seq_type="mrna")
print(GENOMES[GENOMES["sample_id"].isin(["14-11247N", "BLGSP-71-06-00286-99A-01D"])])

# Create table of tumour-normal pairs (with a default unmatched normal genome)
genome_default = shared_config["unmatched_normal_id"]
PAIRS = op.generate_pairs(SAMPLES, genome=("allow_unmatched", genome_default), mrna="no_normal")
print(PAIRS)
```
Line 64 is the call to `PAIRS = op.generate_pairs(...)`

It's obviously reading the config file correctly, am I calling the pairs incorrectly?

**Comment by BrunoGrandePhD** [comment]
I'm looking into this now.

**Comment by BrunoGrandePhD** [comment]
The reason for the error is that I didn't add support for the new `unmatched_normal_ids` parameter in `generate_pairs()`. I was going to implement that later, but I forgot that it was being used in the GAMBL header snakefile.

I've implemented this now. Make sure you use the `unmatched_normal_ids` key in your config file (not `unmatched_normal_id` without an "s"). Then, update the last section in `header.smk` as follows:
```
unmatched_normal_ids = shared_config["unmatched_normal_ids"]
PAIRS = op.generate_pairs(SAMPLES, genome="allow_unmatched", mrna="no_normal", 
                          unmatched_normal_ids=unmatched_normal_ids)
print(PAIRS)
```

Let me know if this fixes the issue.

**Comment by lkhilton** [comment]
There's one more bug: 
```
AssertionError in line 65 of /projects/rmorin/projects/gambl-repos/gambl-lhilton/src/snakemake/header.smk:
There are 0 genome samples matching the normal ID SP116656 (instead of just one).
  File "/projects/rmorin/projects/gambl-repos/gambl-lhilton/src/snakemake/header.smk", line 65, in <module>
  File "/projects/rmorin/software/lcr-modules/oncopipe/oncopipe/__init__.py", line 1343, in generate_pairs
  File "/projects/rmorin/software/lcr-modules/oncopipe/oncopipe/__init__.py", line 1135, in generate_runs
```
Because the SAMPLES table is subset to only `unix_group==gambl` rows, I'm getting an error because the ICGC normal isn't in the table.

**Comment by lkhilton** [comment]
I can confirm though that when I comment out the ICGC normal the pairs table is successfully generated.

**Comment by BrunoGrandePhD** [comment]
Thanks for pointing in the direction of the source of the bug. I've updated the code so that it only looks up the unmatched normal samples for genome builds that exist in the given sample table. Can you give it another try?

**Comment by lkhilton** [comment]
Success!!! Thanks, Bruno!

New life goal: Learn enough Python that I can fix these bugs after you leave in two weeks.

**Comment by rdmorin** [comment]
That's a good goal

**Comment by BrunoGrandePhD** [comment]
Excellent! I'm going to merge once I update the documentation this weekend.

**Comment by BrunoGrandePhD** [comment]
This now fixes #52 and #50. The cookiecutter options now match what's in `generate_pairs()`, _i.e._ `matched_only`, `allow_unmatched`, and `no_normal` (plus `omit`). That was a minor change that I don't expect any issues from. The rest of my updates were changes to the documentation to reflect the new options in oncopipe.

**Pull request merged**
