### PR TITLE
Minor feature additions and bug fixes

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**
In this PR, I've updated the code and docs to expect `__UPDATE__` strings in the default configuration files for anything that required user intervention. Before, the module developer was expected to annotate the values that needed to be updated using `UPDATE` comments. The advantage of using `__UPDATE__` is that I can search for them when setting up the module and raise an informative error regarding a placeholder that needs to be updated. 

I also added two convenience functions for filtering samples to address #32.

### CODE REVIEW

**Comment by BrunoGrandePhD** [comment]
@whelena: Can you think of any way the new approach with `__UPDATE__` can be problematic?

**Comment by whelena** [comment]
> @whelena: Can you think of any way the new approach with `__UPDATE__` can be problematic?

@BrunoGrandePhD i can't see it being a problem

**Comment by BrunoGrandePhD** [comment]
Okay! In that case, feel free to approve the PR and merge it with master. Thanks!

**Comment by BrunoGrandePhD** [comment]
Thanks!

**Pull request merged**
