### PR TITLE
gridss-1.1

### PR DESCRIPTION
**Pull request by lkhilton**
# Pull Request Checklists

**Important:** When opening a pull request, keep only the applicable checklist and delete all other sections.

## Checklist for Updated Module

Updated the changelog to reflect new module features. 

Decided on a minor version update. 
- I'm preserving the old v1.0 so that the new reference files don't force a re-run of all existing GAMBL GRIDSS jobs. 

**IMPORTANT:** I will migrate these files to modules/gridss/1.1 after this PR review is completed.

### CODE REVIEW

**Review by rdmorin — APPROVED** [review]

**Comment by rdmorin** [comment]
Won't all existing cases re-run anyway because there won't be an output in the version 1.1 directory?

**Comment by rdmorin** [comment]
Is this ready for re-review?

**Comment by lkhilton** [comment]
Let me try the bash script function exporting first!

**Comment by lkhilton** [comment]
This is ready for review. To address your question about versioning, I haven't run the hmftools module (which is part of this PR) on GAMBL yet. I have run the gridss module on most of GAMBL. The only difference between gridss 1.0 and 1.1 is the auto-downloading of reference files, so I plan to run gridss 1.0 on all of GAMBL and not run 1.1 on GAMBL at all.

**Review by rdmorin — APPROVED** [review]

**Comment by lkhilton** [comment]
Last approval, I promise!

**Review by rdmorin — APPROVED** [review]

**Pull request merged**
