### PR TITLE
IgCaller module

### PR DESCRIPTION
**Pull request by ppararaj**
# Pull Request Checklists

**Important:** When opening a pull request, keep only the applicable checklist and delete all other sections.

### Required

- [x] I used the cookiecutter template and updated the placeholder rules.

- [x] The snakemake rules follow the [design guidelines](https://lcr-modules.readthedocs.io/en/latest/for_developers.html#module-rules). 

  - [x] All references to the `rules` object (_e.g._ for input files) are wrapped with `str()`.

- [x] Every rule in the module is either listed under `localrules` or has the `threads` and `resources` directives.

- [x] Input and output files are being symlinked into the `CFG["inputs"]` and `CFG["outputs"]` subdirectories, respectively.

- [x] I grouped the input symlinking rule to the next job that uses the input files. 

- [x] I updated the final target rule (`*_all`) to include every output rule.

- [x] I explained important module design decisions in `CHANGELOG.md`.

- [x] I tested the module on real data for all supported `seq_type` values.

- [x] I updated the `default.yaml` configuration file to provide default values for each rule in the module snakefile.

- [x] I did not set any global wildcard constraints. Any/all wildcard constraints are set on a per-rule basis. 

- [x] I ensured that all symbolic links are relative and self-contained (_i.e._ do not point outside of the repository).

- [x] I replaced every value that should (or might need to) be updated in the default configuration file with `__UPDATE__`.

- [x] I recursively searched for all comments containing `TODO` to ensure none were left. For example:

  ```bash
  grep -r TODO modules/<module_name>/1.0
  ```

### If applicable

- [ ] I added subdirectories with large intermediate files to the list of `scratch_subdirectories` in the `default.yaml` configuration file.

### CODE REVIEW

**Comment by ppararaj** [comment]
- Tested on capture and genome BAMs and CRAMs using both paired and unpaired samples

**Comment by lkhilton** [comment]
Looks good, Prasath. I think you could add a rule to auto-install IgCaller though. The MiXCR module has an example of this: 
https://github.com/LCR-BCCRC/lcr-modules/blob/dfa9cc27daa36c242906f9acec900503031c3b55/modules/mixcr/1.1/mixcr.smk#L69-L86

**Comment by ppararaj** [comment]
Added a rule to install IgCaller in a specified directory. Successfully tested the pipeline on all relevant samples.

**Review by lkhilton — APPROVED** [review]
Thanks for adding that, Prasath!

**Pull request merged**
